### ISSUE TITLE
Feat: Guardian gets the list of the proxy wallet they are associated with

### ISSUE THREAD

**Issue by egidiocasati** [nymlab/vectis_fe#10]
As a logged user, i decide to browse the dApp in the guardianship section, to get the list of the proxy wallet i've been associated to.
for each of them, i want to know:

- [ ] what is the multi signature policy / threshold
- [ ] To-be-discussed: if there's a key rotation active request

**Comment by giovanni-orciuolo** [comment]
We agreed many weeks ago that this feature would require an indexer.

For now, the guardian manually inserts the wallet address for which he's a guardian of, and perform operations on the wallet.
