### ISSUE TITLE
Feat: user manages the multisig-policy for guardians

### ISSUE THREAD

**Issue by egidiocasati** [nymlab/vectis_fe#12]
As a logged user, i select my proxy wallet, get the list f guardians and set / modify the threshold policy for multisig.
If N is the number of appointed guardians, i'll be able to set the threshold to K, where 1<=K<=N

**Comment by giovanni-orciuolo** [comment]
https://github.com/nymlab/vectis_fe/commit/692def946058d8d669481198c27ed76649e4368e implements this
