### ISSUE TITLE
Feat: User excludes / deletes a guardian

### ISSUE THREAD

**Issue by egidiocasati** [nymlab/vectis_fe#13]
as a logged User i want to delete one the the appointed guardian accounts for my proxy wallet.
given the threshold K, and the number N of appointed guardians, i'll be able to delete at max Y= N-K, without changing the threshold

**Comment by giovanni-orciuolo** [comment]
https://github.com/nymlab/vectis_fe/commit/692def946058d8d669481198c27ed76649e4368e implements this
