### ISSUE TITLE
New dApp section dedicated to wallet classic features

### ISSUE THREAD

**Issue by egidiocasati** [nymlab/vectis_fe#14]
As a Logged User i want to switch to a view where i can execute wallet basic functions.
If i have more than one proxy wallet, i have to select which one to operate

**Comment by giovanni-orciuolo** [comment]
Please @egidiocasati specify a list of basic functions to implement. At the moment (for each of your own SCWs), you can do the following:

- Transfer funds from the wallet to a recipient address, without using relayers (you need to pay gas)
- Charge the wallet with funds from your private wallet (gas required here too)

**Comment by whalelephant** [comment]
@giovanni-orciuolo 

Let's use this issue as for transferring fund to and from the SCW.

**Comment by giovanni-orciuolo** [comment]
Closed with https://github.com/nymlab/vectis_fe/pull/22
