### ISSUE TITLE
Using Vectis with other DApps

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis_fe#16]
We would like to allow Vectis smart contract owners to use different DApps on Juno. 

In order to do that we will need to allow user to choose their SCW to connect to the DApps, which might be 
1. do a PR to Keplr - https://github.com/chainapsis/keplr-wallet/issues/330
2. user WalletConnect - https://docs.walletconnect.com/smart-wallets
3. other wallet / extension solutions?

This is for post CR2

**Comment by j0nl1** [comment]
I'm closing this issue because we found a solution to connect vectis with other dApps. We implemented our own extension which will be public in short.

I will update this issue pointing to the repository when it will be public.
