### ISSUE TITLE
Publish and use Vectis types from NPM library

### ISSUE THREAD

**Issue by giovanni-orciuolo** [nymlab/vectis_fe#19]
The TypeScript bindings to communicate with Vectis contracts are generated through a script present in the main Vectis repo. The output lives in a directory called `types`.

At the moment, in order to use those types, I just copy and paste that directory in this repo. This ofc is bad because it doesn't version stuff. A good alternative would be to publish the `types` directory from Vectis repo into a separate NPM library which we add as a dependency here (name proposal: `@vectis/types`) and we can version easily.

**Comment by whalelephant** [comment]
This is great for allowing more than 1 UI to use @vectis/types
