### ISSUE TITLE
Enhance guardian experience with indexer

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis_fe#41]
With the incoming indexer providers, such as subQuery, we can provide better guardian experience (and potentially less storage of user to wallet mapping on the factory).

https://subquery.medium.com/subquery-unveils-cosmos-data-indexing-via-juno-integration-7236b2f54707

**Comment by j0nl1** [comment]
I close this issue because the implementation of the indexer is already done in this repository: https://github.com/nymlab/vectis-subquery

Regarding code update you can follow this issue https://github.com/nymlab/vectis_fe/issues/55
